version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(levelname)s:     %(message)s"
    use_colors: True
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: "%(levelname)s:     %(client_addr)s - \"%(request_line)\" %(status_code)s"
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: False
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: False
  security:
    handlers: [file_handler]
    level: INFO
    propagate: False
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5